---

- name: Configs and run victoria storage containers
  become: yes
  import_tasks: vmstorage.yml
  when: "'victoria_storage' in group_names"

- name: Configs and run victoria select containers
  become: yes
  import_tasks: vmselect.yml
  when: 
    - "'victoria_api' in group_names"

- name: Configs and run victoria vminsert containers
  become: yes
  import_tasks: vminsert.yml
  when:
    - "'victoria_api' in group_names"