---

- name: vmselect | Create poject dir
  file:
    name: "{{ compose_projects }}/{{ vmselect_project_name }}"
    state: directory
    mode: "0755"
    owner: "root"
    group: "root"

- name: vmselect | Copy compose files
  template:
    src: "{{ item.j2 }}"
    dest: "{{ item.target }}"
    mode: "0664"
    owner: "root"
    group: "root"
  loop:
    - { j2: 'docker-compose.vmselect.yml.j2', target: "{{ compose_projects }}/{{ vmselect_project_name }}/docker-compose.yml" }
    - { j2: 'vmselect-docker@.service.j2',    target: "/etc/systemd/system/vmselect-docker@.service" }
  notify: 
    - "Restart vmselect"
    - "Sleep for victoria services for 15 seconds"
    - "Check vmselect"

- name: vmselect | UP containers via systemd
  systemd:
    name: "vmselect-docker@{{ vmselect_project_name }}"
    state: started
    enabled: yes
    daemon_reload: yes
  notify:
     - "Sleep for victoria services for 15 seconds"
     - "Check vmselect"